# jenkins.yml
# Sample docker-compose file for running Jenkins container as a service.

version: '3.1'

services:
  main:
    image: techchihuahua/jenkins
    ports:
      - 8080:8080
      - 50000:50000
    secrets:
      - jenkins-user
      - jenkins-pass
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:rw

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true

volumes:
  jenkins_home:

# ------------------------------------------------------------------------
